# KSC Public Record Intelligence — developer commands
#
# Local dev uses the docker-compose stack for infrastructure and runs the
# app processes either in Docker (`make up`) or on the host (`make dev`).

SHELL := /bin/bash
.DEFAULT_GOAL := help

-include .env
export

PY      := .venv/bin/python
PIP     := .venv/bin/pip
PYTEST  := .venv/bin/pytest
RUFF    := .venv/bin/ruff
MYPY    := .venv/bin/mypy
ALEMBIC := .venv/bin/alembic -c apps/api/alembic.ini

# Host-side URLs (services published on localhost by docker-compose).
LOCAL_DATABASE_URL := postgresql+psycopg://$(or $(POSTGRES_USER),ksc):$(or $(POSTGRES_PASSWORD),ksc_dev_password)@localhost:$(or $(POSTGRES_PORT),5432)/$(or $(POSTGRES_DB),ksc)
LOCAL_REDIS_URL    := redis://localhost:6379/0
LOCAL_MINIO        := localhost:9000

HOST_ENV := DATABASE_URL=$(LOCAL_DATABASE_URL) REDIS_URL=$(LOCAL_REDIS_URL) MINIO_ENDPOINT=$(LOCAL_MINIO)

.PHONY: help setup dev up down logs infra migrate migration seed demo-fixture reset-db \
        test test-backend test-frontend test-integration e2e lint format typecheck build ci

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

setup: ## Install Python venv + Node dependencies
	@test -d .venv || python3 -m venv .venv
	$(PIP) install --upgrade pip
	$(PIP) install -e "apps/api[dev]"
	pnpm install

# ---------------------------------------------------------------- run ------

infra: ## Start only postgres, redis, minio (for host-side dev/tests)
	docker compose up -d postgres redis minio minio-init

dev: infra ## Run infra in Docker, then api + web on the host with reload
	@echo "API  → http://localhost:8000   Web → http://localhost:3000"
	@trap 'kill 0' EXIT; \
	  ( $(HOST_ENV) $(ALEMBIC) upgrade head && $(HOST_ENV) .venv/bin/ksc-seed && \
	    $(HOST_ENV) .venv/bin/uvicorn ksc_api.main:app --reload --port 8000 --app-dir apps/api/src ) & \
	  ( cd apps/web && pnpm dev ) & \
	  wait

up: ## Build and start the full stack in Docker
	docker compose up --build -d
	@echo "Web → http://localhost:3000   API → http://localhost:8000/docs   MinIO console → http://localhost:9001"

down: ## Stop the stack (keeps volumes)
	docker compose down

logs: ## Tail logs from all services
	docker compose logs -f --tail=100

# ----------------------------------------------------------- database ------

migrate: ## Apply migrations to the local database (host → localhost)
	$(HOST_ENV) $(ALEMBIC) upgrade head

migration: ## Create a new autogenerated migration: make migration m="describe change"
	$(HOST_ENV) $(ALEMBIC) revision --autogenerate -m "$(m)"

seed: ## Seed public case metadata for KSC-BC-2020-06 (idempotent)
	$(HOST_ENV) .venv/bin/ksc-seed

demo-fixture: ## Load the synthetic KSC-DEMO-0000 evidence fixture (idempotent; no real records)
	$(HOST_ENV) .venv/bin/ksc-demo-fixture

reset-db: ## DESTROY local database volumes and recreate from migrations
	docker compose down -v
	docker compose up -d postgres redis minio minio-init
	@echo "waiting for postgres…"; sleep 5
	$(MAKE) migrate seed

# ------------------------------------------------------------- quality ------

test: test-backend test-frontend ## Run backend unit+integration and frontend tests

test-backend: ## Backend unit + integration tests (integration needs `make infra`)
	$(HOST_ENV) $(PYTEST)

test-unit: ## Backend unit tests only (no infrastructure needed)
	$(PYTEST) tests/unit

test-integration: ## Backend integration tests only
	$(HOST_ENV) $(PYTEST) tests/integration

test-frontend: ## Frontend unit/component tests
	pnpm --filter @ksc/web test

e2e: ## Playwright E2E (needs `pnpm exec playwright install` once, and the stack running)
	pnpm e2e

lint: ## Lint everything (ruff, eslint, prettier check)
	$(RUFF) check .
	$(RUFF) format --check .
	pnpm lint
	pnpm format:check

typecheck: ## Type-check (mypy, tsc)
	$(MYPY)
	pnpm typecheck

format: ## Auto-format (ruff format, prettier)
	$(RUFF) format .
	$(RUFF) check --fix .
	pnpm format

build: ## Production build of the web app
	pnpm build

ci: lint typecheck test ## What CI runs
