"""Phase 6 evidence model.

Import order matters only for readability; SQLAlchemy resolves string
relationship targets once every module is imported. Everything is registered
on `Base.metadata` by importing this package (Alembic relies on that).
"""

from ksc_api.models.actor import Location, Organization, Person, PersonAlias, Witness
from ksc_api.models.ai import (
    AiOutput,
    AiOutputCitation,
    AiOutputSource,
    AiRetrievalSource,
    AiRun,
    PromptVersion,
)
from ksc_api.models.appeal import (
    AppealIssue,
    AppealIssueSource,
    AppealMissingMaterial,
    RedTeamFinding,
    RedTeamReview,
    StatementComparison,
)
from ksc_api.models.audit_log import AuditLog
from ksc_api.models.case import Case
from ksc_api.models.citation import (
    UNRESOLVED_DISPLAY,
    Citation,
    RecordIdentifier,
    normalize_identifier,
)
from ksc_api.models.document import (
    Document,
    DocumentChunk,
    DocumentIngestionState,
    DocumentPage,
    DocumentParagraph,
    DocumentSection,
    DocumentVersion,
)
from ksc_api.models.enums import (
    INGESTION_FAILURE_STATUSES,
    PUBLIC_VISIBILITIES,
    AiRunStatus,
    AnswerBlockKind,
    ArgumentResponseKind,
    ArtifactStatus,
    CitationType,
    ClaimOrigin,
    ClaimStance,
    DatePrecision,
    DateType,
    DocumentVersionType,
    EntityKind,
    ExaminationType,
    FindingLinkType,
    IdentifierKind,
    IngestionItemStatus,
    IngestionJobStatus,
    Party,
    RelationshipOrigin,
    RelationshipType,
    ResolutionMethod,
    ResolutionState,
    SourceSystem,
    TextExtractionMethod,
    VerificationState,
    Visibility,
    WitnessIdentityStatus,
)
from ksc_api.models.evidence import (
    Argument,
    ArgumentResponse,
    Claim,
    ClaimMention,
    Event,
    Exhibit,
    Finding,
    FindingEvidenceLink,
    Incident,
)
from ksc_api.models.graph import NODE_FK_COLUMNS, GraphNode, Relationship
from ksc_api.models.hearing import Hearing, Transcript, TranscriptSegment, WitnessAppearance
from ksc_api.models.ingestion import IngestionJob, IngestionJobItem
from ksc_api.models.media import (
    COMPARISON_CLASSES,
    COURT_MEDIA_STATUSES,
    CourtMediaLink,
    ExternalSource,
    MediaItem,
    MediaStatement,
    MediaStatementComparison,
)
from ksc_api.models.operations import (
    ArtifactAcquisition,
    ArtifactQuarantine,
    ProcessingRun,
    SourceRecordSnapshot,
)
from ksc_api.models.research import ResearchNote, ResearchNoteCitation
from ksc_api.models.source_record import SourceRecord

__all__ = [
    "COMPARISON_CLASSES",
    "COURT_MEDIA_STATUSES",
    "INGESTION_FAILURE_STATUSES",
    "NODE_FK_COLUMNS",
    "PUBLIC_VISIBILITIES",
    "UNRESOLVED_DISPLAY",
    "AiOutput",
    "AiOutputCitation",
    "AiOutputSource",
    "AiRetrievalSource",
    "AiRun",
    "AiRunStatus",
    "AnswerBlockKind",
    "AppealIssue",
    "AppealIssueSource",
    "AppealMissingMaterial",
    "Argument",
    "ArgumentResponse",
    "ArgumentResponseKind",
    "ArtifactAcquisition",
    "ArtifactQuarantine",
    "ArtifactStatus",
    "AuditLog",
    "Case",
    "Citation",
    "CitationType",
    "Claim",
    "ClaimMention",
    "ClaimOrigin",
    "ClaimStance",
    "CourtMediaLink",
    "DatePrecision",
    "DateType",
    "Document",
    "DocumentChunk",
    "DocumentIngestionState",
    "DocumentPage",
    "DocumentParagraph",
    "DocumentSection",
    "DocumentVersion",
    "DocumentVersionType",
    "EntityKind",
    "Event",
    "ExaminationType",
    "Exhibit",
    "ExternalSource",
    "Finding",
    "FindingEvidenceLink",
    "FindingLinkType",
    "GraphNode",
    "Hearing",
    "IdentifierKind",
    "Incident",
    "IngestionItemStatus",
    "IngestionJob",
    "IngestionJobItem",
    "IngestionJobStatus",
    "Location",
    "MediaItem",
    "MediaStatement",
    "MediaStatementComparison",
    "Organization",
    "Party",
    "Person",
    "PersonAlias",
    "ProcessingRun",
    "PromptVersion",
    "RecordIdentifier",
    "RedTeamFinding",
    "RedTeamReview",
    "Relationship",
    "RelationshipOrigin",
    "RelationshipType",
    "ResearchNote",
    "ResearchNoteCitation",
    "ResolutionMethod",
    "ResolutionState",
    "SourceRecord",
    "SourceRecordSnapshot",
    "SourceSystem",
    "StatementComparison",
    "TextExtractionMethod",
    "Transcript",
    "TranscriptSegment",
    "VerificationState",
    "Visibility",
    "Witness",
    "WitnessAppearance",
    "WitnessIdentityStatus",
    "normalize_identifier",
]
